import { RawItem } from "../../src/types";

export const initialSeedItems: RawItem[] = [
  {
    id: "item-arxiv-mcp-agentic",
    source: "arxiv",
    sourceUrl: "https://arxiv.org/abs/2502.14856",
    title: "Dynamic Tool Discovery and Asynchronous Protocol Negotiation in Multi-Agent MCP Systems",
    summary:
      "We introduce an autonomous tool discovery layer for Model Context Protocol (MCP) servers, enabling decentralized agents to discover, negotiate schema parameters, and execute multi-step tool calls without centralized orchestration. Benchmarks show a 41% reduction in token overhead for long-horizon agent trajectories.",
    contentType: "paper",
    publishedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "Stanford AI Lab & DeepMind Collaboration",
    score: 96,
  },
  {
    id: "item-hn-claude-37",
    source: "hackernews",
    sourceUrl: "https://news.ycombinator.com/item?id=43158021",
    title: "Claude 3.7 Sonnet: Hybrid Reasoning with Dynamic Thinking Budgets",
    summary:
      "Anthropic introduces Claude 3.7 Sonnet, the first hybrid frontier model combining instantaneous response capabilities with extended thinking tokens controllable via API. Major improvements on SWE-bench (70.3%) and tool invocation reliability.",
    contentType: "news",
    publishedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "Anthropic Engineering",
    score: 98,
    rawMetadata: { points: 1420, comments: 840 },
  },
  {
    id: "item-news-claude-37",
    source: "company_blog",
    sourceUrl: "https://www.anthropic.com/news/claude-3-7-sonnet",
    title: "Anthropic Releases Claude 3.7 Sonnet with Flexible Thinking Architecture",
    summary:
      "Official release announcement detailing the hybrid reasoning paradigm, developer SDK updates for token budgeting, and native Model Context Protocol support across enterprise deployments.",
    contentType: "news",
    publishedAt: new Date(Date.now() - 3600000 * 5.2).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "Anthropic",
    score: 97,
  },
  {
    id: "item-arxiv-maddpg-grid",
    source: "arxiv",
    sourceUrl: "https://arxiv.org/abs/2502.09912",
    title: "Decentralized Credit Assignment in Multi-Agent Reinforcement Learning for Grid-Scale Resource Scheduling",
    summary:
      "Investigating multi-agent policy gradients (MADDPG variants) with asynchronous actor-critic updates for dynamic EV fleet charging and electrical microgrid balancing under stochastic load fluctuations.",
    contentType: "paper",
    publishedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "Berkeley AI Research (BAIR)",
    score: 95,
  },
  {
    id: "item-ph-fastmcp",
    source: "producthunt",
    sourceUrl: "https://www.producthunt.com/posts/fastmcp-v2",
    title: "FastMCP 2.0: High-Performance TypeScript and Python SDK for Building AI Tool Servers",
    summary:
      "Create production-ready Model Context Protocol (MCP) servers in under 10 lines of code with automatic OpenAPI schema generation, SSE streaming, and OAuth2 authentication out of the box.",
    contentType: "tool",
    publishedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "FastMCP Team",
    score: 92,
    rawMetadata: { upvotes: 680 },
  },
  {
    id: "item-yt-karpathy-thinking",
    source: "youtube",
    sourceUrl: "https://www.youtube.com/watch?v=kYJ7x9cK1qg",
    title: "How Reasoning Models Actually Think: Reinforcement Learning & Test-Time Search Explained",
    summary:
      "Andrej Karpathy breaks down the mechanics of test-time compute, monte carlo tree search for LLM reasoning, process reward models (PRMs), and how reinforcement learning over chain-of-thought bridges the gap to autonomous agent execution.",
    contentType: "video",
    publishedAt: new Date(Date.now() - 3600000 * 16).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "Andrej Karpathy",
    score: 94,
    rawMetadata: { views: "480K" },
  },
  {
    id: "item-reddit-localllama-deepseek",
    source: "reddit",
    sourceUrl: "https://www.reddit.com/r/LocalLLaMA/comments/deepseek_r1_distill_eval",
    title: "DeepSeek-R1 Distilled 7B running on Apple Silicon outperforms Claude 3.5 Sonnet on Coding Benchmarks",
    summary:
      "Community benchmark reproduction with quantized GGUF models running locally on Mac M3 Max, demonstrating 68 tokens/sec with sub-second time-to-first-token in agent coding harnesses.",
    contentType: "discussion",
    publishedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "r/LocalLLaMA",
    score: 89,
    rawMetadata: { upvotes: 2150, comments: 412 },
  },
  {
    id: "item-arxiv-spatial-cv",
    source: "arxiv",
    sourceUrl: "https://arxiv.org/abs/2502.18910",
    title: "Spatial-VLM: Real-Time 3D Grounding and Affordance Estimation for Embodied Vision Agents",
    summary:
      "A lightweight vision-language model trained on synchronized RGB-D streams that predicts 3D bounding primitives and spatial contact affordances at 35 FPS on edge devices.",
    contentType: "paper",
    publishedAt: new Date(Date.now() - 3600000 * 22).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "MIT CSAIL & Google DeepMind",
    score: 91,
  },
  {
    id: "item-hn-cursor-composer-agents",
    source: "hackernews",
    sourceUrl: "https://news.ycombinator.com/item?id=43162019",
    title: "Building Multi-File Agentic Workflows with MCP in Modern IDEs",
    summary:
      "Discussion on how modern developer tools use AST indexing, vector search, and background terminal execution to enable autonomous AI developer loops.",
    contentType: "discussion",
    publishedAt: new Date(Date.now() - 3600000 * 26).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "Hacker News",
    score: 88,
    rawMetadata: { points: 510, comments: 230 },
  },
  {
    id: "item-yt-twominutepapers-robotics",
    source: "youtube",
    sourceUrl: "https://www.youtube.com/watch?v=v8X_z9q8PqA",
    title: "Google DeepMind's New Vision-Action Model Learns Complex Dexterity in Minutes",
    summary:
      "Two Minute Papers review of the latest reinforcement learning breakthroughs in physical robot manipulation combining synthetic trajectory generation and diffusion policies.",
    contentType: "video",
    publishedAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "Two Minute Papers",
    score: 86,
    rawMetadata: { views: "320K" },
  },
  {
    id: "item-news-nvidia-blackwell-infra",
    source: "newsapi",
    sourceUrl: "https://techcrunch.com/2025/02/20/nvidia-accelerates-ai-datacenter-liquid-cooling-specs",
    title: "NVIDIA Unveils Next-Generation AI Cluster Architectures for High-Concurrency Agent Inference",
    summary:
      "New reference designs targeting massive context caching and low-latency token streaming for multi-agent workflows across thousands of interconnected GPUs.",
    contentType: "news",
    publishedAt: new Date(Date.now() - 3600000 * 34).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "TechCrunch AI",
    score: 85,
  },
  {
    id: "item-ph-smolagents-huggingface",
    source: "producthunt",
    sourceUrl: "https://www.producthunt.com/posts/smolagents-by-huggingface",
    title: "Smolagents 2.0: Ultra-Lightweight Code-First Agent Framework by Hugging Face",
    summary:
      "A pure Python framework where agents write and execute Python code actions instead of JSON tool blobs, dramatically reducing parsing errors and boosting complex arithmetic tasks.",
    contentType: "tool",
    publishedAt: new Date(Date.now() - 3600000 * 38).toISOString(),
    ingestedAt: new Date().toISOString(),
    authorOrChannel: "Hugging Face",
    score: 93,
    rawMetadata: { upvotes: 950 },
  },
];
